# Generated by Django 5.2.8 on 2025-11-20 21:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], validators=[django.core.validators.MinValueValidator(limit_value=0, message='Se intentó ingresar un día de la semana negativo'), django.core.validators.MaxValueValidator(limit_value=6, message='Se intentó ingresar un día de la semana que no existe (mayor a domingo).')], verbose_name='Día de la semana')),
                ('intervalo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=5, message='El intervalo tiene que ser de por lo menos 5 minutos.')])),
                ('inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('fin', models.TimeField(verbose_name='Hora de fin')),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.emprendimiento')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('duracion', models.PositiveIntegerField(help_text='Duración del servicio en minutos.', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.FloatField(default=0.0, help_text='Precio del servicio (no puede ser negativo).', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('color', models.CharField(blank=True, help_text='Color del servicio en el calendario.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Debe ser un color hex válido, por ejemplo #FF5733', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('activo', models.BooleanField(default=True)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.emprendimiento')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fin', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('cliente_nombre', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre del cliente')),
                ('cliente_contacto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Contacto del cliente')),
                ('nota', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.emprendimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='turnos.servicio')),
            ],
        ),
    ]
