# Generated by Django 5.2.8 on 2025-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/perfil/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/perfil/'),
        ),
    ]
